-- DATABASE: RONSTORE

-- product_id
-- product_name
-- product_price
-- product_stock
-- size
-- color

SELECT * FROM RONSTORE;
SELECT * FROM AVAILABLE_SIZES;

CREATE TABLE AVAILABLE_SIZES(
    PRODUCTID INT,
    SMALL INT,
    MEDIUM INT,
    LARGE INT
);

INSERT INTO AVAILABLE_SIZES (SIZES_ID, SMALL, MEDIUM, LARGE) VALUES
(1, 20, 15, 17),
(2, 25, 20, 22),
(3, 30, 25, 27),
(4, 35, 30, 32),
(5, 40, 35, 37),
(6, 45, 40, 42),
(7, 50, 45, 47),
(8, 55, 50, 52),
(9, 60, 55, 57),
(10, 65, 60, 62);

SELECT PRODUCTID, PRODUCTNAME, SMALL, MEDIUM, LARGE FROM RONSTORE
INNER JOIN AVAILABLE_SIZES ON RONSTORE.PRODUCTID = AVAILABLE_SIZES.SIZES_ID;

ALTER TABLE AVAILABLE_SIZES DROP COLUMN PRODUCTID;
ALTER TABLE AVAILABLE_SIZES ADD SIZES_ID INT;

CREATE TABLE COLORS(
    COLOR_ID INT PRIMARY KEY,
    COLOR_NAME VARCHAR(50)
);

ALTER TABLE RONSTORE ADD COLOR_ID INT;
ALTER TABLE RONSTORE ADD SIZES_ID INT;

INSERT INTO COLORS (COLOR_ID, COLOR_NAME) VALUES
(1, 'Red'),
(2, 'Blue'),
(3, 'Black'),
(4, 'White');

UPDATE RONSTORE SET
COLOR_ID = CASE 
    WHEN PRODUCTID = 1 THEN 1
    WHEN PRODUCTID = 2 THEN 2
    WHEN PRODUCTID = 3 THEN 3
    WHEN PRODUCTID = 4 THEN 4
    WHEN PRODUCTID = 5 THEN 1
    WHEN PRODUCTID = 6 THEN 2
    WHEN PRODUCTID = 7 THEN 3
    WHEN PRODUCTID = 8 THEN 4
    WHEN PRODUCTID = 9 THEN 1
    WHEN PRODUCTID = 10 THEN 2
    ELSE NULL
END;

UPDATE RONSTORE SET
SIZES_ID = CASE 
    WHEN PRODUCTID = 1 THEN 1
    WHEN PRODUCTID = 2 THEN 2
    WHEN PRODUCTID = 3 THEN 3
    WHEN PRODUCTID = 4 THEN 4
    WHEN PRODUCTID = 5 THEN 5
    WHEN PRODUCTID = 6 THEN 6
    WHEN PRODUCTID = 7 THEN 7
    WHEN PRODUCTID = 8 THEN 8
    WHEN PRODUCTID = 9 THEN 9
    WHEN PRODUCTID = 10 THEN 10
    ELSE NULL
END;
